/**
 * Remediation Tickets — turns audit findings into actionable tickets that can be
 * pushed into the client's tooling (Jira, Confluence, Smartsheet, SharePoint).
 *
 * Whiteboard flow: "Report Results / Remediations → become Tickets".
 *
 * This module is pure (no DB/IO): it shapes findings into tickets and serializes
 * them into the formats those tools ingest — CSV (Jira / Smartsheet / SharePoint
 * import), JSON (generic API), and Markdown (Confluence). Real OAuth API push is
 * a future step; import files cover the integration today with no credentials.
 */

import { AUDIT_COMPONENTS } from '@/lib/components';

export interface TicketFinding {
  questionId: string;
  componentNumber: number;
  questionText: string;
  riskWeight: string;            // 'critical' | 'high' | 'medium' | 'low'
  response: string;              // expects 'no' | 'partial' (the gaps)
  auditorNotes: string | null;
  remediation: string | null;
}

export type TicketPriority = 'Highest' | 'High' | 'Medium' | 'Low';

export interface RemediationTicket {
  key: string;
  summary: string;
  componentNumber: number;
  component: string;             // "§7123(c)(2) — Encryption"
  citation: string;             // "§7123(c)(2)"
  priority: TicketPriority;
  riskWeight: string;
  response: string;
  labels: string[];
  description: string;
}

const PRIORITY: Record<string, TicketPriority> = {
  critical: 'Highest',
  high: 'High',
  medium: 'Medium',
  low: 'Low',
};

// Stable ordering: most severe first, then by component.
const SEVERITY_RANK: Record<string, number> = { critical: 0, high: 1, medium: 2, low: 3 };

function shorten(s: string, n: number): string {
  const clean = s.replace(/\s+/g, ' ').trim();
  return clean.length <= n ? clean : clean.slice(0, n - 1).trimEnd() + '…';
}

/** Build remediation tickets from gap findings (response = no / partial). */
export function buildTickets(findings: TicketFinding[]): RemediationTicket[] {
  const tickets = findings
    .filter(f => f.response === 'no' || f.response === 'partial')
    .map<RemediationTicket>(f => {
      const c = AUDIT_COMPONENTS.find(x => x.number === f.componentNumber);
      const citation = c?.citation ?? `§7123(c)(${f.componentNumber})`;
      const title = c?.title ?? `Component ${f.componentNumber}`;
      const gap = f.response === 'no' ? 'Control not implemented' : 'Control partially implemented';

      const descriptionParts = [
        `Finding: ${gap} (auditor response: ${f.response.toUpperCase()}).`,
        '',
        `Requirement — ${citation} (${title}):`,
        f.questionText,
      ];
      if (f.auditorNotes && f.auditorNotes.trim()) {
        descriptionParts.push('', 'Auditor notes:', f.auditorNotes.trim());
      }
      descriptionParts.push(
        '',
        'Recommended remediation:',
        f.remediation?.trim() || 'Define and implement a control that satisfies this requirement, then re-test.',
        '',
        'Source: ShieldAudit — CPPA §7123 cybersecurity audit.'
      );

      return {
        key: `SA-${f.questionId}`,
        summary: `[${citation}] ${shorten(f.questionText, 90)}`,
        componentNumber: f.componentNumber,
        component: `${citation} — ${title}`,
        citation,
        priority: PRIORITY[f.riskWeight] ?? 'Medium',
        riskWeight: f.riskWeight,
        response: f.response,
        labels: ['ShieldAudit', 'CCPA', citation.replace(/[^A-Za-z0-9]/g, ''), f.riskWeight],
        description: descriptionParts.join('\n'),
      };
    });

  tickets.sort(
    (a, b) =>
      (SEVERITY_RANK[a.riskWeight] ?? 9) - (SEVERITY_RANK[b.riskWeight] ?? 9) ||
      a.componentNumber - b.componentNumber
  );
  return tickets;
}

// ── Serializers ──────────────────────────────────────────────────────────────

/** Jira / Smartsheet / SharePoint CSV import format. */
export function ticketsToCsv(tickets: RemediationTicket[]): string {
  const esc = (v: string) => '"' + String(v ?? '').replace(/"/g, '""') + '"';
  const header = ['Summary', 'Issue Type', 'Priority', 'Component', 'Labels', 'Description'];
  const rows = tickets.map(t =>
    [t.summary, 'Task', t.priority, t.component, t.labels.join(' '), t.description].map(esc).join(',')
  );
  return [header.map(esc).join(','), ...rows].join('\r\n');
}

/** Generic JSON for API-based ingestion. */
export function ticketsToJson(tickets: RemediationTicket[]): string {
  return JSON.stringify(
    { generatedAt: new Date().toISOString(), source: 'ShieldAudit', count: tickets.length, tickets },
    null,
    2
  );
}

/** Confluence-friendly Markdown (summary table + per-ticket sections). */
export function ticketsToMarkdown(tickets: RemediationTicket[], orgName: string): string {
  const lines: string[] = [
    `# Remediation Tickets — ${orgName}`,
    '',
    `Generated by ShieldAudit from the CPPA §7123 cybersecurity audit — ${tickets.length} open remediation item(s).`,
    '',
    '| Key | Priority | Component | Summary |',
    '|---|---|---|---|',
    ...tickets.map(t => `| ${t.key} | ${t.priority} | ${t.citation} | ${t.summary.replace(/\|/g, '\\|')} |`),
    '',
  ];
  for (const t of tickets) {
    lines.push(
      `## ${t.key} — ${t.summary}`,
      '',
      `- **Priority:** ${t.priority} (${t.riskWeight})`,
      `- **Component:** ${t.component}`,
      `- **Labels:** ${t.labels.join(', ')}`,
      '',
      ...t.description.split('\n'),
      ''
    );
  }
  return lines.join('\n');
}
