# =============================================================================
# ShieldAudit — Dockerfile (offline SQLite, self-contained)
#
# No external database, no Clerk, no cloud. Everything runs in one container;
# audit data persists in a Docker volume mounted at /data.
#
# Stages:
#   deps    — install npm dependencies (+ build toolchain for better-sqlite3)
#   builder — next build
#   runner  — minimal runtime; on boot: drizzle-kit push → seed → next start
# =============================================================================

# ── Stage 1: dependencies ────────────────────────────────────────────────────
FROM node:20-bookworm-slim AS deps
WORKDIR /app

# Build toolchain for native modules (better-sqlite3). Debian/glibc base so the
# compiled binary works in the equally-glibc runner stage.
RUN apt-get update \
 && apt-get install -y --no-install-recommends python3 make g++ \
 && rm -rf /var/lib/apt/lists/*

COPY package.json package-lock.json* ./
# package-lock.json is generated by npm 11. node:20 bundles npm 10.8.2, whose
# strict `npm ci` misreads npm-11 optional-dependency entries (e.g. the
# @esbuild/* platform packages) and fails with "Missing ... from lock file".
# Align npm to the lockfile's generator before installing.
RUN npm install -g npm@11 && npm ci

# ── Stage 2: build ───────────────────────────────────────────────────────────
FROM node:20-bookworm-slim AS builder
WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1

COPY --from=deps /app/node_modules ./node_modules
COPY . .

RUN npm run build

# ── Stage 3: runtime ─────────────────────────────────────────────────────────
FROM node:20-bookworm-slim AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME=0.0.0.0
# SQLite database lives on a mounted volume so audit data survives restarts.
ENV DATABASE_PATH=/data/shieldaudit.db
# Sensible client defaults — no cloud services required out of the box.
ENV STORAGE_MODE=mock
ENV STRIPE_MODE=mock

RUN groupadd --system --gid 1001 nodejs \
 && useradd  --system --uid 1001 --gid nodejs nextjs

# App + the files the entrypoint needs at runtime (drizzle-kit push + seed)
COPY --from=builder /app/public            ./public
COPY --from=builder /app/.next             ./.next
COPY --from=builder /app/node_modules      ./node_modules
COPY --from=builder /app/package.json      ./package.json
COPY --from=builder /app/next.config.mjs   ./next.config.mjs
COPY --from=builder /app/drizzle.config.ts ./drizzle.config.ts
COPY --from=builder /app/src/db/schema.ts  ./src/db/schema.ts
COPY --from=builder /app/docker/seed.mjs   ./docker/seed.mjs
COPY --from=builder /app/docker-entrypoint.sh ./docker-entrypoint.sh

# Normalize entrypoint line endings (Windows checkouts may add CRLF, which
# breaks the shebang), make it executable, and create a writable data dir owned
# by the runtime user so a fresh named volume is writable.
RUN sed -i 's/\r$//' /app/docker-entrypoint.sh \
 && chmod +x /app/docker-entrypoint.sh \
 && mkdir -p /data && chown -R nextjs:nodejs /data

# pdfkit resolves AFM font files via __dirname; Turbopack can rewrite that to
# /ROOT. serverExternalPackages prevents bundling; this symlink is a fallback.
RUN ln -sfn /app /ROOT

USER nextjs
EXPOSE 3000
VOLUME ["/data"]

ENTRYPOINT ["/app/docker-entrypoint.sh"]
CMD ["node_modules/.bin/next", "start"]
