/**
 * Document C — System Security Plan generator (DOCX).
 *
 * AI-drafted §7123-aligned SSP. Retain for 5 years per Cal. Code Regs. tit. 11, §7123.
 * Classification: CONFIDENTIAL — Attorney-Client Privileged.
 */

import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
} from 'docx';

export interface SspSectionData {
  componentNumber: number;
  title: string;
  citation: string;
  narrative: string;
  gaps: string[];
}

export interface SspDocxInput {
  orgName: string;
  legalEntity: string | null;
  auditPeriodStart: string | null;
  auditPeriodEnd: string | null;
  generatedAt: string;
  executiveOverview: string;
  sections: SspSectionData[];
  aiGenerated: boolean;
}

function fmtDate(d: string | null | undefined): string {
  if (!d) return 'N/A';
  return new Date(d).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
}

function body(text: string, opts?: { italic?: boolean; color?: string }): Paragraph {
  return new Paragraph({
    children: [new TextRun({ text, italics: opts?.italic, color: opts?.color })],
    spacing: { after: 120 },
  });
}

export async function generateSspDocx(input: SspDocxInput): Promise<Buffer> {
  const { orgName, legalEntity, auditPeriodStart, auditPeriodEnd, generatedAt, executiveOverview, sections, aiGenerated } = input;

  const children: Paragraph[] = [
    new Paragraph({
      children: [new TextRun({ text: 'SYSTEM SECURITY PLAN', bold: true, size: 48, color: '0F1B2D' })],
      alignment: AlignmentType.CENTER,
      spacing: { before: 400, after: 120 },
    }),
    new Paragraph({
      children: [new TextRun({ text: 'Cal. Code Regs. tit. 11, §7123  ·  NIST SP 800-53 Rev 5', size: 22, italics: true, color: '666666' })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 300 },
    }),
    new Paragraph({
      children: [new TextRun({ text: orgName, bold: true, size: 30, color: '0F1B2D' })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 60 },
    }),
    new Paragraph({
      children: [new TextRun({ text: legalEntity ?? '', size: 22, color: '555555' })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 200 },
    }),
    new Paragraph({
      children: [new TextRun({ text: `Audit Period: ${fmtDate(auditPeriodStart)} – ${fmtDate(auditPeriodEnd)}`, size: 20, color: '555555' })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 40 },
    }),
    new Paragraph({
      children: [new TextRun({ text: `Generated: ${generatedAt}`, size: 20, color: '888888' })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 40 },
    }),
    new Paragraph({
      children: [new TextRun({ text: 'CONFIDENTIAL — ATTORNEY-CLIENT PRIVILEGED', bold: true, size: 18, color: 'CC0000' })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 400 },
    }),

    new Paragraph({ text: 'Executive Overview', heading: HeadingLevel.HEADING_1, spacing: { before: 200, after: 120 } }),
    body(executiveOverview),

    new Paragraph({ text: 'Control Implementation by Component', heading: HeadingLevel.HEADING_1, spacing: { before: 300, after: 120 } }),
  ];

  for (const s of sections) {
    children.push(
      new Paragraph({ text: `${s.citation} — ${s.title}`, heading: HeadingLevel.HEADING_2, spacing: { before: 240, after: 60 } }),
      body(s.narrative)
    );
    if (s.gaps.length > 0) {
      children.push(
        new Paragraph({
          children: [new TextRun({ text: 'Remediation items:', bold: true, color: 'B91C1C' })],
          spacing: { after: 60 },
        })
      );
      for (const g of s.gaps) {
        children.push(
          new Paragraph({
            children: [new TextRun({ text: g, color: '334155' })],
            bullet: { level: 0 },
            spacing: { after: 40 },
            indent: { left: 360 },
          })
        );
      }
    }
  }

  children.push(
    new Paragraph({ text: '', spacing: { after: 200 } }),
    body(
      'This System Security Plan was generated by the ShieldAudit platform from the cybersecurity audit responses' +
        (aiGenerated ? ', assisted by AI document analysis,' : '') +
        ' and must be reviewed and approved by the auditor of record before use. Retain for 5 years per Cal. Code Regs. tit. 11, §7123.',
      { italic: true, color: '888888' }
    )
  );

  const doc = new Document({
    creator: 'ShieldAudit Platform',
    title: `System Security Plan — ${orgName}`,
    description: 'CPPA System Security Plan per Cal. Code Regs. tit. 11, §7123',
    sections: [{ properties: {}, children }],
  });

  return Buffer.from(await Packer.toBuffer(doc));
}
