export const dynamic = 'force-dynamic';

/**
 * Integrations hub — /dashboard/integrations
 *
 * Surfaces the integrations ShieldAudit can push to. Active today (env-driven,
 * no OAuth): Jira issue creation from remediation tickets, Slack/Teams/webhook
 * notifications, and ticket exports (CSV/JSON/MD). Everything else is on the
 * roadmap and listed here so the direction is visible.
 */

import { Plug, Bell, CheckCircle2, Circle, Clock, Download, Ticket } from 'lucide-react';
import { integrationStatus } from '@/lib/integrations/config';
import { JiraPushButton, NotifyButton } from './IntegrationActions';
import SettingsForm from './SettingsForm';

async function fetchTicketCount(userId: string): Promise<number> {
  const { db } = await import('@/db');
  const { userRoles, assessments, answers } = await import('@/db/schema');
  const { eq, and, desc, inArray } = await import('drizzle-orm');

  const roleRows = await db.select({ orgId: userRoles.orgId }).from(userRoles).where(eq(userRoles.clerkUserId, userId)).limit(1);
  if (roleRows.length === 0) return 0;
  const { orgId } = roleRows[0];
  const a = await db.select({ id: assessments.id }).from(assessments).where(eq(assessments.orgId, orgId)).orderBy(desc(assessments.createdAt)).limit(1);
  if (a.length === 0) return 0;
  const rows = await db
    .select({ id: answers.id })
    .from(answers)
    .where(and(eq(answers.assessmentId, a[0].id), eq(answers.orgId, orgId), inArray(answers.response, ['no', 'partial'])));
  return rows.length;
}

function StatusBadge({ on }: { on: boolean }) {
  return on ? (
    <span className="inline-flex items-center gap-1 rounded px-2 py-0.5 text-[10px] font-medium text-emerald-400 bg-emerald-400/10 border border-emerald-400/30">
      <CheckCircle2 size={10} /> Configured
    </span>
  ) : (
    <span className="inline-flex items-center gap-1 rounded px-2 py-0.5 text-[10px] font-medium text-slate-400 bg-slate-500/10 border border-slate-500/30">
      <Circle size={10} /> Not configured
    </span>
  );
}

const ROADMAP = [
  { name: 'SSO — Okta / Microsoft Entra ID', why: 'SAML/OIDC + SCIM. Required for enterprise login; also an MFA evidence source.' },
  { name: 'Evidence connectors — Okta, AWS, Tenable/Qualys, CrowdStrike/Intune', why: 'Pull control evidence at the source to auto-fill the audit (§7123(e) auditor-observed evidence).' },
  { name: 'Document storage — SharePoint / Google Drive / S3', why: 'Evidence locker + 5-year retention.' },
  { name: 'Confluence / Notion', why: 'Publish the audit report and SSP.' },
  { name: 'GRC / privacy — OneTrust, Vanta, Drata, Secureframe', why: 'Share/ingest compliance evidence.' },
  { name: 'e-Signature — DocuSign / Adobe Sign', why: 'Sign Document B (executive certification, §7122(a)(5)).' },
];

export default async function IntegrationsPage() {
  const status = await integrationStatus();
  let ticketCount = 0;
  try { ticketCount = await fetchTicketCount('local-user'); } catch {}
  const notifierConfigured = status.slack || status.teams || status.webhook;

  return (
    <div className="min-h-full px-8 py-8">
      <div className="mb-6 max-w-3xl">
        <div className="flex items-center gap-3 mb-2">
          <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-teal-400/10">
            <Plug size={20} className="text-teal-400" aria-hidden="true" />
          </div>
          <div>
            <p className="text-xs font-medium uppercase tracking-wider text-teal-400">Integrations</p>
            <h1 className="font-sora text-2xl font-semibold text-slate-100">Connect your tools</h1>
          </div>
        </div>
        <p className="text-sm text-slate-400 leading-relaxed">
          Push audit findings and alerts into the systems your team already uses. Enter credentials in{' '}
          <span className="text-slate-300">Credentials</span> below — they&apos;re encrypted at rest and never shown
          back to you — or provide them as environment variables (e.g. in your{' '}
          <span className="font-mono text-xs text-slate-300">.env</span> or Docker compose).
        </p>
      </div>

      <div className="max-w-3xl mb-4">
        <SettingsForm />
      </div>

      <div className="max-w-3xl space-y-4">
        {/* Jira */}
        <section className="rounded-xl border border-navy-600 bg-navy-600/20 p-5">
          <div className="flex items-start justify-between gap-3 mb-2">
            <div className="flex items-center gap-2">
              <Ticket size={16} className="text-teal-400" />
              <h2 className="font-sora text-sm font-semibold text-slate-100">Jira</h2>
            </div>
            <StatusBadge on={status.jira} />
          </div>
          <p className="text-xs text-slate-400 leading-relaxed mb-3">
            Create Jira issues from the {ticketCount} remediation ticket(s) generated by the audit (one issue per
            No/Partial finding, with priority, labels, and remediation steps).
          </p>
          {status.jira ? (
            <JiraPushButton ticketCount={ticketCount} />
          ) : (
            <p className="text-[11px] text-slate-500">
              Enter your Jira details in <span className="text-slate-400">Credentials</span> above (or set the JIRA_* env vars).
            </p>
          )}
        </section>

        {/* Notifications */}
        <section className="rounded-xl border border-navy-600 bg-navy-600/20 p-5">
          <div className="flex items-start justify-between gap-3 mb-2">
            <div className="flex items-center gap-2">
              <Bell size={16} className="text-teal-400" />
              <h2 className="font-sora text-sm font-semibold text-slate-100">Notifications</h2>
            </div>
            <div className="flex items-center gap-1.5">
              <span className={`text-[10px] ${status.slack ? 'text-emerald-400' : 'text-slate-600'}`}>Slack</span>
              <span className={`text-[10px] ${status.teams ? 'text-emerald-400' : 'text-slate-600'}`}>Teams</span>
              <span className={`text-[10px] ${status.webhook ? 'text-emerald-400' : 'text-slate-600'}`}>Webhook</span>
            </div>
          </div>
          <p className="text-xs text-slate-400 leading-relaxed mb-3">
            Post an audit summary (overall score, traffic-light counts, open remediation items) to your channels.
          </p>
          {notifierConfigured ? (
            <NotifyButton />
          ) : (
            <p className="text-[11px] text-slate-500">
              Add a webhook URL in <span className="text-slate-400">Credentials</span> above (or set the *_WEBHOOK_URL env vars).
            </p>
          )}
        </section>

        {/* Exports */}
        <section className="rounded-xl border border-navy-600 bg-navy-600/20 p-5">
          <div className="flex items-center gap-2 mb-2">
            <Download size={16} className="text-teal-400" />
            <h2 className="font-sora text-sm font-semibold text-slate-100">Ticket exports</h2>
            <span className="inline-flex items-center gap-1 rounded px-2 py-0.5 text-[10px] font-medium text-emerald-400 bg-emerald-400/10 border border-emerald-400/30">Always available</span>
          </div>
          <p className="text-xs text-slate-400 leading-relaxed mb-3">
            Import-ready files for Jira, Smartsheet, SharePoint (CSV), Confluence (Markdown), or any API (JSON).
          </p>
          <div className="flex flex-wrap items-center gap-2">
            {[['csv', 'CSV'], ['json', 'JSON'], ['md', 'Markdown']].map(([fmt, label]) => (
              <a
                key={fmt}
                href={`/api/tickets/export?format=${fmt}`}
                className="inline-flex items-center gap-1.5 rounded-lg border border-navy-600 bg-navy-600/40 px-3 py-1.5 text-xs font-medium text-slate-300 hover:text-teal-400 hover:border-teal-400/30 transition-colors"
              >
                <Download size={12} /> {label}
              </a>
            ))}
          </div>
        </section>
      </div>

      {/* Roadmap */}
      <div className="mt-8 max-w-3xl">
        <h2 className="text-xs font-semibold uppercase tracking-wider text-slate-500 mb-3">Planned</h2>
        <div className="space-y-2">
          {ROADMAP.map(r => (
            <div key={r.name} className="flex items-start gap-3 rounded-lg border border-navy-700 bg-navy-700/30 px-4 py-3">
              <Clock size={14} className="mt-0.5 text-slate-600 flex-shrink-0" />
              <div>
                <p className="text-sm text-slate-300">{r.name}</p>
                <p className="text-xs text-slate-500">{r.why}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
