/**
 * Audit-summary content builders shared by the publish integrations.
 *
 * - Confluence storage format (XHTML) for page bodies.
 * - Notion block objects for page children.
 *
 * Both render the same thing the remediation-ticket export shows: a summary
 * table plus a section per open finding. Source data is RemediationTicket[].
 */

import 'server-only';
import type { RemediationTicket } from '@/lib/tickets';
import type { NotionBlock } from './notion';

function esc(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

/** Confluence storage-format (XHTML) body. */
export function auditSummaryHtml(orgName: string, tickets: RemediationTicket[]): string {
  const date = new Date().toISOString().slice(0, 10);
  const intro = `<p>Generated by ShieldAudit from the CPPA §7123 cybersecurity audit on ${date} — ${tickets.length} open remediation item(s).</p>`;
  if (tickets.length === 0) {
    return `<h1>Audit Summary — ${esc(orgName)}</h1>${intro}<p>No open remediation items. All assessed controls were marked implemented.</p>`;
  }
  const rows = tickets
    .map(
      (t) =>
        `<tr><td>${esc(t.key)}</td><td>${esc(t.priority)}</td><td>${esc(t.citation)}</td><td>${esc(t.summary)}</td></tr>`
    )
    .join('');
  const table = `<table><thead><tr><th>Key</th><th>Priority</th><th>Component</th><th>Summary</th></tr></thead><tbody>${rows}</tbody></table>`;
  const sections = tickets
    .map((t) => {
      const desc = t.description
        .split('\n')
        .map((l) => (l.trim() ? `<p>${esc(l)}</p>` : ''))
        .join('');
      return `<h2>${esc(t.key)} — ${esc(t.summary)}</h2><p><strong>Priority:</strong> ${esc(t.priority)} (${esc(t.riskWeight)}) · <strong>Component:</strong> ${esc(t.component)}</p>${desc}`;
    })
    .join('');
  return `<h1>Audit Summary — ${esc(orgName)}</h1>${intro}${table}${sections}`;
}

/** Notion page children (heading_2 / paragraph / bulleted_list_item). */
export function auditSummaryNotionBlocks(orgName: string, tickets: RemediationTicket[]): NotionBlock[] {
  const date = new Date().toISOString().slice(0, 10);
  const rt = (content: string) => [{ type: 'text', text: { content: content.slice(0, 1900) } }];
  const p = (text: string): NotionBlock => ({ object: 'block', type: 'paragraph', paragraph: { rich_text: rt(text) } });
  const h2 = (text: string): NotionBlock => ({ object: 'block', type: 'heading_2', heading_2: { rich_text: rt(text) } });
  const bullet = (text: string): NotionBlock => ({
    object: 'block',
    type: 'bulleted_list_item',
    bulleted_list_item: { rich_text: rt(text) },
  });

  const blocks: NotionBlock[] = [
    p(`Audit Summary — ${orgName}`),
    p(`Generated by ShieldAudit from the CPPA §7123 cybersecurity audit on ${date} — ${tickets.length} open remediation item(s).`),
  ];
  if (tickets.length === 0) {
    blocks.push(p('No open remediation items. All assessed controls were marked implemented.'));
    return blocks;
  }
  for (const t of tickets) {
    blocks.push(h2(`${t.key} — ${t.summary}`));
    blocks.push(bullet(`Priority: ${t.priority} (${t.riskWeight})`));
    blocks.push(bullet(`Component: ${t.component}`));
    blocks.push(p(t.description.replace(/\n+/g, ' ')));
  }
  return blocks;
}
